In [3]:
import numpy as np

In [6]:
a = np.arange(15).reshape(3, 5)

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a = np.arange(15)

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a = np.arange(15).reshape(2,2)

ValueError: cannot reshape array of size 15 into shape (2,2)

In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.ndim

2

In [ ]:
a = np.arange(16).reshape(4,4)

In [12]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a = np.arange(16).reshape(2,8)

In [14]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [15]:
a = np.arange(16).reshape(8,2)

In [16]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [17]:
a = np.arange(16).reshape(1,16)

In [18]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [19]:
a.ndim

2

In [20]:
a.dtype.name

'int64'

In [21]:
a.itemsize

8

In [22]:
a.size

16

In [23]:
type(a)

numpy.ndarray

In [24]:
a = np.array([1,2,3])

In [25]:
a

array([1, 2, 3])

In [26]:
a.dtype

dtype('int64')

In [27]:
a = np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [28]:
a = np.array([(1,2,3),(4,5,6)])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [1]:
np.ones((2,3,4,5,6,7,8,9,10,11,12,13,14))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [ ]:
np.ones((2,3,4,5,6,7,8,9,10,11,12,13,14))

In [1]:
import numpy as np

In [5]:
np.ones((2,3,4,5,6))

array([[[[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1